// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.
// @pikit/pi-adapter/providers/amazon-bedrock: pi-ai 1.1.0's Amazon Bedrock provider (id `amazon-bedrock`), by subpath: an app carries only the providers it imports.
// Server only (SERVER_ONLY_EXPORTS, packages/cli/src/registry/imports.ts): it needs Node; a component importing it targets ["server"].

export * from "@earendil-works/pi-ai/providers/amazon-bedrock";
