// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.
// @pikit/pi-adapter/providers/deepseek: pi-ai 1.1.0's DeepSeek provider (id `deepseek`), by subpath: an app carries only the providers it imports.

export * from "@earendil-works/pi-ai/providers/deepseek";
