// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.
// @pikit/pi-adapter/providers/google-vertex: pi-ai 1.0.3's Google Vertex AI provider (id `google-vertex`), by subpath: an app carries only the providers it imports.
// Server only (SERVER_ONLY_EXPORTS, packages/cli/src/registry/imports.ts): it needs Node; a component importing it targets ["server"].

export * from "@earendil-works/pi-ai/providers/google-vertex";
