// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.
// @pikit/pi-adapter/providers/huggingface: pi-ai 1.0.3's Hugging Face provider (id `huggingface`), by subpath: an app carries only the providers it imports.

export * from "@earendil-works/pi-ai/providers/huggingface";
