// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.
// @pikit/pi-adapter/providers/kimi-coding: pi-ai 1.1.0's Kimi For Coding provider (id `kimi-coding`), by subpath: an app carries only the providers it imports.

export * from "@earendil-works/pi-ai/providers/kimi-coding";
