// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.
// @pikit/pi-adapter/providers/opencode-go: pi-ai 1.0.3's OpenCode Go provider (id `opencode-go`), by subpath: an app carries only the providers it imports.

export * from "@earendil-works/pi-ai/providers/opencode-go";
