// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.
// @pikit/pi-adapter/providers/qwen-token-plan-cn: pi-ai 1.0.3's Qwen Token Plan CN provider (id `qwen-token-plan-cn`), by subpath: an app carries only the providers it imports.

export * from "@earendil-works/pi-ai/providers/qwen-token-plan-cn";
