// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.
// @pikit/pi-adapter/providers/vercel-ai-gateway: pi-ai 1.0.3's Vercel AI Gateway provider (id `vercel-ai-gateway`), by subpath: an app carries only the providers it imports.

export * from "@earendil-works/pi-ai/providers/vercel-ai-gateway";
