// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.
// @pikit/pi-adapter/providers/xiaomi-token-plan-ams: pi-ai 1.1.0's Xiaomi Token Plan AMS provider (id `xiaomi-token-plan-ams`), by subpath: an app carries only the providers it imports.

export * from "@earendil-works/pi-ai/providers/xiaomi-token-plan-ams";
