// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.
// @pikit/pi-adapter/providers/zai-coding-cn: pi-ai 1.1.0's Z.AI Coding CN provider (id `zai-coding-cn`), by subpath: an app carries only the providers it imports.

export * from "@earendil-works/pi-ai/providers/zai-coding-cn";
