/**
 * The adapter's provider subpaths, generated from the pinned pi-ai (run at each Pi pin bump,
 * docs/upstream/README.md):
 *
 * - `@pikit/pi-adapter/providers/<id>`: one file per pi-ai built-in provider factory, re-exporting
 *   `@earendil-works/pi-ai/providers/<id>` (`groqProvider`, `openaiProvider`…). One subpath per id and
 *   no barrel: a component imports the one provider it provides, so a Worker bundles only that one
 *   and Bun, unbundled, loads only that one (MANIFESTO 5).
 * - `@pikit/pi-adapter/api/<name>`: one file per lazy API wrapper of pi-ai
 *   (`@earendil-works/pi-ai/api/<name>.lazy`: `openAICompletionsApi`…), which a provider written in a
 *   project passes to `createProvider` (`@pikit/pi-adapter/provider`). The implementation loads at
 *   the first request.
 *
 * The ids are pi-ai's `getBuiltinProviders()` plus the ids `builtinProviders()` constructs (a purely
 * dynamic provider such as Radius has no catalog entry of its own). `faux` is not a built-in: its
 * subpath (`providers/faux.ts`) is written by hand, as `provider.ts` is.
 *
 * The files carry `GENERATED`; a generated file whose id is gone is deleted. `package.json`'s exports
 * keep the hand-written entries in their order, then the generated ones, sorted. Which of them need
 * Node is not generated: `SERVER_ONLY_EXPORTS` (packages/cli/src/registry/imports.ts) says so, and
 * the files' headers repeat it.
 *
 *   bun scripts/pi-providers.ts           write the files and package.json
 *   bun scripts/pi-providers.ts --check   exit 1 when they differ from what pi-ai gives
 *
 * `pi-providers.test.ts` runs the check in `bun test`.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";
import { SERVER_ONLY_EXPORTS } from "../packages/cli/src/registry/imports.ts";

export const ADAPTER_DIR = join(import.meta.dir, "..", "packages", "pi-adapter");
const ADAPTER = "@pikit/pi-adapter";
/** The first line of every generated file. */
export const GENERATED = "// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.";

interface PiAiProviders {
  getBuiltinProviders(): string[];
  builtinProviders(): { id: string; name: string }[];
}

/** pi-ai's `dist/`, as the adapter resolves it. */
export function piAiDist(): string {
  return dirname(dirname(Bun.resolveSync("@earendil-works/pi-ai/providers/all", ADAPTER_DIR)));
}

/** pi-ai's version, from its package.json next to `dist/`. */
function piAiVersion(dist: string): string {
  return (JSON.parse(readFileSync(join(dist, "..", "package.json"), "utf8")) as { version: string }).version;
}

/** Every built-in provider id with its display name: `getBuiltinProviders()` plus what `builtinProviders()` constructs. */
export async function builtinIds(): Promise<Map<string, string>> {
  const all = (await import(pathToFileURL(join(piAiDist(), "providers", "all.js")).href)) as PiAiProviders;
  const names = new Map<string, string>();
  for (const provider of all.builtinProviders()) names.set(provider.id, provider.name);
  for (const id of all.getBuiltinProviders()) if (!names.has(id)) names.set(id, id);
  return new Map([...names].sort(([a], [b]) => a.localeCompare(b)));
}

/** pi-ai's lazy API wrappers: `dist/api/<name>.lazy.js` → `<name>`. */
export function lazyApis(): string[] {
  return readdirSync(join(piAiDist(), "api"))
    .filter((file) => file.endsWith(".lazy.js"))
    .map((file) => file.slice(0, -".lazy.js".length))
    .sort();
}

function serverOnlyNote(subpath: string): string {
  return SERVER_ONLY_EXPORTS.includes(`${ADAPTER}/${subpath}`)
    ? "\n// Server only (SERVER_ONLY_EXPORTS, packages/cli/src/registry/imports.ts): it needs Node; a component importing it targets [\"server\"]."
    : "";
}

/** What the generator writes: adapter-relative path → content, and the generated exports. */
export interface Plan {
  files: Map<string, string>;
  exports: Record<string, string>;
}

export async function plan(): Promise<Plan> {
  const dist = piAiDist();
  const version = piAiVersion(dist);
  const files = new Map<string, string>();
  const exports: Record<string, string> = {};
  for (const [id, name] of await builtinIds()) {
    if (!existsSync(join(dist, "providers", `${id}.js`))) {
      throw new Error(`pi-ai ${version} has the built-in provider "${id}" but no providers/${id} module: map its id to its module here`);
    }
    const subpath = `providers/${id}`;
    files.set(
      `src/${subpath}.ts`,
      `${GENERATED}\n// ${ADAPTER}/${subpath}: pi-ai ${version}'s ${name} provider (id \`${id}\`), by subpath: an app carries only the providers it imports.${serverOnlyNote(subpath)}\n\nexport * from "@earendil-works/pi-ai/${subpath}";\n`,
    );
    exports[`./${subpath}`] = `./src/${subpath}.ts`;
  }
  for (const api of lazyApis()) {
    const subpath = `api/${api}`;
    files.set(
      `src/${subpath}.ts`,
      `${GENERATED}\n// ${ADAPTER}/${subpath}: pi-ai ${version}'s lazy \`${api}\` API, for \`createProvider\` (${ADAPTER}/provider): its implementation loads at the first request.${serverOnlyNote(subpath)}\n\nexport * from "@earendil-works/pi-ai/${subpath}.lazy";\n`,
    );
    exports[`./${subpath}`] = `./src/${subpath}.ts`;
  }
  return { files, exports };
}

/** The generated files on disk, adapter-relative: those in `providers/` and `api/` that start with `GENERATED`. */
function generatedOnDisk(): string[] {
  return ["providers", "api"].flatMap((dir) => {
    const path = join(ADAPTER_DIR, "src", dir);
    if (!existsSync(path)) return [];
    return readdirSync(path)
      .filter((file) => file.endsWith(".ts") && readFileSync(join(path, file), "utf8").startsWith(GENERATED))
      .map((file) => `src/${dir}/${file}`);
  });
}

interface PackageJson {
  exports: Record<string, string>;
}

/** package.json's exports: the hand-written entries in their order, then `generated`. */
function withExports(pkg: PackageJson, generated: Record<string, string>, onDisk: Set<string>): Record<string, string> {
  const own = Object.entries(pkg.exports).filter(([, target]) => !onDisk.has(target.replace(/^\.\//, "")) && !Object.values(generated).includes(target));
  return { ...Object.fromEntries(own), ...generated };
}

/** What differs between the plan and the disk, one line each; empty when nothing does. */
export async function drift(): Promise<string[]> {
  const { files, exports } = await plan();
  const problems: string[] = [];
  for (const [path, content] of files) {
    const full = join(ADAPTER_DIR, path);
    if (!existsSync(full)) problems.push(`packages/pi-adapter/${path} is missing`);
    else if (readFileSync(full, "utf8") !== content) problems.push(`packages/pi-adapter/${path} differs`);
  }
  for (const path of generatedOnDisk()) if (!files.has(path)) problems.push(`packages/pi-adapter/${path} is generated for a provider pi-ai no longer has`);
  const pkg = JSON.parse(readFileSync(join(ADAPTER_DIR, "package.json"), "utf8")) as PackageJson;
  const expected = withExports(pkg, exports, new Set(generatedOnDisk()));
  if (JSON.stringify(expected) !== JSON.stringify(pkg.exports)) problems.push("packages/pi-adapter/package.json's exports differ from the generated subpaths");
  return problems;
}

export async function write(): Promise<void> {
  const { files, exports } = await plan();
  const onDisk = new Set(generatedOnDisk());
  for (const path of onDisk) if (!files.has(path)) rmSync(join(ADAPTER_DIR, path));
  for (const [path, content] of files) {
    mkdirSync(dirname(join(ADAPTER_DIR, path)), { recursive: true });
    writeFileSync(join(ADAPTER_DIR, path), content);
  }
  const pkgPath = join(ADAPTER_DIR, "package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as PackageJson;
  pkg.exports = withExports(pkg, exports, onDisk);
  writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
}

if (import.meta.main) {
  if (process.argv.includes("--check")) {
    const problems = await drift();
    for (const problem of problems) console.error(`✗ ${problem}`);
    if (problems.length > 0) {
      console.error("run `bun scripts/pi-providers.ts`");
      process.exit(1);
    }
    console.info("the adapter's provider and API subpaths match pi-ai");
  } else {
    await write();
    console.info("wrote the adapter's provider and API subpaths");
  }
}
