/**
 * tool-mcp's `beforeDeploy`: the deployment's `up` calls it before it builds or bundles
 * (`component.json`: `"hooks": { "beforeDeploy": "deploy.ts" }`), and deploys nothing when it reports
 * a problem.
 *
 * It reaches each server in config from this machine, as the doctor check does (`listNamed`), and
 * writes what each listed of the tools config names into `seed.ts`, which `index.ts` imports: the
 * build bundles it (Cloudflare) or copies it into the image (Docker). A start that finds no listing in
 * `storage.kv` (on Cloudflare, a new conversation's Durable Object) then describes the tools from it
 * and reaches no server. A server that cannot be reached, refuses the token or lacks a named tool is
 * a problem, and `seed.ts` stays as it was.
 *
 * - **No secret.** The seed holds each server's URL and, of each named tool, only what the kept
 *   listing holds (name, title, description, inputSchema, annotations): never a token nor a header.
 * - **No churn.** It holds no time, and `write` leaves the file alone when its text is the same: a
 *   deploy changes `seed.ts` only when a server's tools changed. Commit it, so that a build without
 *   the CLI (Workers Builds, a "Deploy to Cloudflare" button, `docker build`) bundles it too.
 */

import { listNamed, serversOf } from "./doctor.ts";
import { keptTool, type McpSeed, type SeedTool } from "./index.ts";

/** The file this hook writes, in `src/pikit/tool-mcp/`. */
export const SEED_FILE = "seed.ts";

/** What the deployment gives the hook (`hooks.beforeDeploy`). */
export interface BeforeDeployIO {
  /** This component's config in `pikit.config.ts`. */
  config: Readonly<Record<string, unknown>>;
  /** A variable of the environment or `.env`: the servers' tokens. */
  get(name: string): string | undefined;
  /** Writes `text` to `file` of `src/pikit/tool-mcp/` unless it already holds it; whether it changed. */
  write(file: string, text: string): boolean;
  say(line: string): void;
}

/** Lists each server's named tools and writes them into `seed.ts`; resolves with the problems (empty when done). */
export async function beforeDeploy(io: BeforeDeployIO): Promise<string[]> {
  const servers = Object.entries(serversOf(io.config));
  const listed = await Promise.all(servers.map(([name, settings]) => listNamed(name, settings, io.get)));
  const problems = listed.flatMap((result) => ("problems" in result ? result.problems : []));
  if (problems.length > 0) return problems;

  const seed: McpSeed = {};
  servers.forEach(([name, settings], index) => {
    const result = listed[index];
    if (result === undefined || "problems" in result) return;
    // Loosely typed in the seed: whatever JSON the server sent must type-check there.
    seed[name] = { url: settings.url, tools: Object.fromEntries(result.tools.map((tool) => [tool.name, keptTool(tool) as unknown as SeedTool])) };
  });
  const changed = io.write(SEED_FILE, seedModule(seed));
  if (servers.length > 0 || changed) {
    const what = `the tools of ${servers.length} MCP server${servers.length === 1 ? "" : "s"}`;
    io.say(`✓ tool-mcp: ${what} in src/pikit/tool-mcp/${SEED_FILE}${changed ? " (changed: commit it)" : ", unchanged"}`);
  }
  return [];
}

/** The text of `seed.ts` holding `seed`: with no server, the file as installed. */
export function seedModule(seed: McpSeed): string {
  return `${HEADER}\nimport type { McpSeed } from "./index.ts";\n\nexport const seed: McpSeed = ${JSON.stringify(seed, null, 2)};\n`;
}

const HEADER = `/**
 * Generated by tool-mcp's \`beforeDeploy\` (deploy.ts), which \`pikit up\` runs before it builds: do not
 * edit. For each MCP server in config, its URL and the tools config names, as the server listed them
 * (name, title, description, inputSchema, annotations); never a token or a header.
 *
 * A start that finds no listing in \`storage.kv\` describes the tools from here, for the same URL, and
 * reaches no server. Commit this file: a build without the CLI (Workers Builds, a "Deploy to
 * Cloudflare" button, \`docker build\`) bundles what is here. Empty, a start without a kept listing
 * reaches the servers.
 */
`;
