/**
 * tool-mcp's `beforeDeploy` (`deploy.ts`): the seed it writes, and what stops a deploy. Each MCP
 * server is a local stand-in on a free port: no test reaches the network or needs a real token.
 * `write` is a fake that keeps the files; one case imports the module it wrote.
 */

import { afterAll, expect, test } from "bun:test";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createFakeMcpServer, type FakeMcpServer } from "@pikit/pi-adapter/mcp/testing";
import { type BeforeDeployIO, beforeDeploy, SEED_FILE, seedModule } from "./deploy.ts";
import { doctor } from "./doctor.ts";
import type { McpSeed } from "./index.ts";

const TOKEN = "mcp-deploy-token-0123456789";
const TOOLS = [
  {
    name: "ask_question",
    title: "Ask a question",
    description: "Asks a question about a repository.",
    inputSchema: { type: "object", properties: { repoName: { type: "string" } } },
    annotations: { readOnlyHint: true },
  },
  { name: "open_issue", inputSchema: { type: "object" } },
  { name: "not_named", description: "Not in config: never in the seed.", inputSchema: { type: "object" } },
];

const stops: (() => unknown)[] = [];
afterAll(async () => {
  for (const stop of stops) await stop();
});

function serve(server: FakeMcpServer): string {
  const http = Bun.serve({ port: 0, hostname: "127.0.0.1", fetch: server.fetch });
  stops.push(() => http.stop(true));
  return `http://127.0.0.1:${http.port}/mcp`;
}

/** An IO over `config` and `env`, whose `write` keeps the files it is given and `say` the lines. */
function io(config: Record<string, unknown>, env: Record<string, string> = {}, files: Record<string, string> = {}) {
  const said: string[] = [];
  const value: BeforeDeployIO = {
    config,
    get: (name) => env[name],
    write(file, text) {
      if (files[file] === text) return false;
      files[file] = text;
      return true;
    },
    say: (line) => void said.push(line),
  };
  return { io: value, files, said };
}

test("it writes each server's named tools, and only what a start needs, into seed.ts; nothing secret", async () => {
  const server = createFakeMcpServer({ tools: TOOLS, token: TOKEN });
  const url = serve(server);
  const config = { servers: { wiki: { url, secret: "WIKI_MCP_TOKEN", headers: { "x-team": "blue" }, tools: ["open_issue", "ask_question"] } } };
  const run = io(config, { WIKI_MCP_TOKEN: TOKEN });

  expect(await beforeDeploy(run.io)).toEqual([]);
  const text = run.files[SEED_FILE] ?? "";
  expect(text).toStartWith("/**\n * Generated by tool-mcp's `beforeDeploy`");
  expect(text).not.toContain(TOKEN);
  expect(text).not.toContain("WIKI_MCP_TOKEN");
  expect(text).not.toContain("x-team");
  expect(text).not.toContain("not_named");
  expect(text).not.toContain("listedAt");
  expect(run.said).toEqual(["✓ tool-mcp: the tools of 1 MCP server in src/pikit/tool-mcp/seed.ts (changed: commit it)"]);

  // The module it wrote is what a start reads.
  const dir = mkdtempSync(join(tmpdir(), "tool-mcp-seed-"));
  stops.push(() => rmSync(dir, { recursive: true, force: true }));
  writeFileSync(join(dir, "index.ts"), "export type McpSeed = Record<string, unknown>;\n");
  writeFileSync(join(dir, SEED_FILE), text);
  const { seed } = (await import(join(dir, SEED_FILE))) as { seed: McpSeed };
  expect(seed).toEqual({
    wiki: {
      url,
      tools: {
        open_issue: { name: "open_issue", inputSchema: { type: "object" } },
        ask_question: TOOLS[0] as McpSeed[string]["tools"][string],
      },
    },
  });
  // What it wrote is what the doctor check calls up to date: no note.
  expect(await doctor({ config, get: (name) => ({ WIKI_MCP_TOKEN: TOKEN })[name] }, seed as never)).toEqual({ problems: [], notes: [] });
});

test("a deploy whose servers list the same tools leaves seed.ts as it is", async () => {
  const url = serve(createFakeMcpServer({ tools: TOOLS }));
  const files: Record<string, string> = {};
  const config = { servers: { wiki: { url, tools: ["ask_question"] } } };
  await beforeDeploy(io(config, {}, files).io);
  const again = io(config, {}, files);
  expect(await beforeDeploy(again.io)).toEqual([]);
  expect(again.said).toEqual(["✓ tool-mcp: the tools of 1 MCP server in src/pikit/tool-mcp/seed.ts, unchanged"]);
});

test("a server that cannot be reached, lacks a named tool or has no token is a problem, and seed.ts is not written", async () => {
  const url = serve(createFakeMcpServer({ tools: TOOLS }));
  const run = io(
    {
      servers: {
        wiki: { url, tools: ["ask_question", "delete_everything"] },
        gone: { url: "http://127.0.0.1:9/mcp", tools: ["anything"] },
        private: { url, secret: "PRIVATE_MCP_TOKEN", tools: ["ask_question"] },
      },
    },
    {},
  );
  const problems = await beforeDeploy(run.io);
  expect(problems).toHaveLength(3);
  expect(problems[0]).toBe('the MCP server "wiki" has no tool "delete_everything" (it has: ask_question, open_issue, not_named)');
  expect(problems[1]).toStartWith('the MCP server "gone" (http://127.0.0.1:9/mcp) could not list its tools: ');
  expect(problems[2]).toContain("needs the secret PRIVATE_MCP_TOKEN");
  expect(run.files).toEqual({});
  expect(run.said).toEqual([]);
});

test("without servers, seed.ts is the empty seed", async () => {
  const run = io({});
  expect(await beforeDeploy(run.io)).toEqual([]);
  expect(run.files[SEED_FILE]).toBe(seedModule({}));
  expect(seedModule({})).toEndWith('import type { McpSeed } from "./index.ts";\n\nexport const seed: McpSeed = {};\n');
});
