/**
 * Generated by tool-mcp's `beforeDeploy` (deploy.ts), which `pikit up` runs before it builds: do not
 * edit. For each MCP server in config, its URL and the tools config names, as the server listed them
 * (name, title, description, inputSchema, annotations); never a token or a header.
 *
 * A start that finds no listing in `storage.kv` describes the tools from here, for the same URL, and
 * reaches no server. Commit this file: a build without the CLI (Workers Builds, a "Deploy to
 * Cloudflare" button, `docker build`) bundles what is here. Empty, a start without a kept listing
 * reaches the servers.
 */

import type { McpSeed } from "./index.ts";

export const seed: McpSeed = {};
