// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.
// @pikit/pi-adapter/api/google-generative-ai: pi-ai 1.1.0's lazy `google-generative-ai` API, for `createProvider` (@pikit/pi-adapter/provider): its implementation loads at the first request.

export * from "@earendil-works/pi-ai/api/google-generative-ai.lazy";
