// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.
// @pikit/pi-adapter/api/google-vertex: pi-ai 1.1.0's lazy `google-vertex` API, for `createProvider` (@pikit/pi-adapter/provider): its implementation loads at the first request.
// Server only (SERVER_ONLY_EXPORTS, packages/cli/src/registry/imports.ts): it needs Node; a component importing it targets ["server"].

export * from "@earendil-works/pi-ai/api/google-vertex.lazy";
