// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.
// @pikit/pi-adapter/api/openrouter-images: pi-ai 1.0.3's lazy `openrouter-images` API, for `createProvider` (@pikit/pi-adapter/provider): its implementation loads at the first request.

export * from "@earendil-works/pi-ai/api/openrouter-images.lazy";
