// Generated by scripts/pi-providers.ts from the pinned pi-ai: do not edit, run it at each Pi pin bump.
// @pikit/pi-adapter/api/typesafe-system-one: pi-ai 1.0.3's lazy `typesafe-system-one` API, for `createProvider` (@pikit/pi-adapter/provider): its implementation loads at the first request.

export * from "@earendil-works/pi-ai/api/typesafe-system-one.lazy";
